document.addEventListener('DOMContentLoaded', () => {
    if (!window.auth.currentUser || window.auth.currentUser.type !== 'teacher') return;

    const teacherId = window.auth.currentUser.id;
    const teacherName = window.auth.currentUser.name;
    let currentPage = 'dashboard';

    function escHtml(s) { return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;'); }

    function generateAIDesc() {
        const title = document.getElementById('tdCourseTitle').value.trim();
        const category = document.getElementById('tdCourseCategory').value;
        const stage = document.getElementById('tdCourseStage').value;
        if (!title) { showToast('أدخل اسم الكورس أولاً', 'error'); return; }
        if (!window.AI_ASSISTANT) { showToast('المساعد الذكي غير متاح حالياً', 'error'); return; }
        showToast('جاري التوليد بالذكاء الاصطناعي... ⏳', 'info');
        AI_ASSISTANT.generateCourseContent(title, category, stage).then(desc => {
            document.getElementById('tdCourseDesc').value = desc;
            showToast('✅ تم توليد الوصف بالذكاء الاصطناعي!');
        }).catch(() => {
            showToast('تعذر الاتصال بالذكاء الاصطناعي، استخدم القالب السريع', 'error');
            autoGenerateDesc();
        });
    }

    function autoGenerateDesc() {
        const title = document.getElementById('tdCourseTitle').value.trim();
        const category = document.getElementById('tdCourseCategory').value;
        const stage = document.getElementById('tdCourseStage').value;
        if (!title) { showToast('أدخل اسم الكورس أولاً', 'error'); return; }
        const stageMap = { all: 'جميع المراحل', primary: 'المرحلة الابتدائية', middle: 'المرحلة الإعدادية', high: 'المرحلة الثانوية' };
        const catMap = { languages: 'اللغات', science: 'العلوم', math: 'الرياضيات', physics: 'الفيزياء', chemistry: 'الكيمياء', social: 'الاجتماعيات', tech: 'التكنولوجيا' };
        const templates = [
            `انطلق في رحلة تعليمية ممتعة مع كورس "${title}" المصمم خصيصاً لـ ${stageMap[stage] || 'جميع المراحل'}.`,
            `هذا الكورس في مجال ${catMap[category] || category} يقدم محتوى ثرياً ومنهجية حديثة تجمع بين النظري والتطبيقي.`,
            `ستتعلم عبر سلسلة من الدروس التفاعلية المصممة بعناية لضمان فهم عميق ومستدام للمادة العلمية.`,
            `ماذا ستتعلم؟\n• أساسيات متينة في ${catMap[category] || category}\n• مهارات تطبيقية وعملية\n• تمارين واختبارات تقييمية\n• مشاريع عملية لتعزيز الفهم`,
            `الكورس مناسب للطلاب في ${stageMap[stage] || 'جميع المراحل'} الذين يرغبون في تطوير مستواهم وتحقيق التفوق الأكاديمي.`,
            `سجل الآن وابدأ رحلتك نحو التميز مع LookaGenius!`
        ];
        const desc = templates.join('\n\n');
        document.getElementById('tdCourseDesc').value = desc;
        showToast('تم توليد وصف الكورس بنجاح ✨');
    }

    function getYouTubeEmbedUrl(url) {
        if (!url) return '';
        let videoId = '';
        // youtube.com/watch?v=VIDEO_ID
        const match1 = url.match(/(?:youtube\.com\/watch\?v=|youtube\.com\/embed\/)([a-zA-Z0-9_-]{11})/);
        if (match1) videoId = match1[1];
        // youtu.be/VIDEO_ID
        const match2 = url.match(/youtu\.be\/([a-zA-Z0-9_-]{11})/);
        if (match2) videoId = match2[1];
        if (!videoId) return url; // return as-is if not a YouTube URL
        return 'https://www.youtube-nocookie.com/embed/' + videoId + '?modestbranding=1&rel=0&controls=1&iv_load_policy=3&hl=ar&cc_load_policy=1';
    }

    function formatDate(d) {
        if (!d) return '-';
        try { return new Date(d).toLocaleDateString('ar-EG', {year:'numeric',month:'short',day:'numeric'}); } catch(e) { return d; }
    }

    function showToast(msg, type) {
        let toast = document.getElementById('teacherToast');
        if (!toast) {
            toast = document.createElement('div');
            toast.id = 'teacherToast';
            toast.style.cssText = 'position:fixed;bottom:25px;left:50%;transform:translateX(-50%) translateY(80px);background:rgba(5,5,20,0.95);backdrop-filter:blur(20px);border:1px solid var(--border-color);border-radius:14px;padding:14px 24px;display:flex;align-items:center;gap:10px;z-index:2000;transition:0.4s cubic-bezier(0.175,0.885,0.32,1.275);opacity:0;pointer-events:none;font-weight:600;font-size:0.9rem;font-family:var(--font-main);';
            document.body.appendChild(toast);
        }
        toast.className = '';
        toast.style.opacity = '1';
        toast.style.transform = 'translateX(-50%) translateY(0)';
        toast.style.borderColor = type === 'error' ? 'var(--neon-pink)' : type === 'info' ? 'var(--warning)' : 'var(--success)';
        toast.innerHTML = `<i class="fa-solid ${type==='error'?'fa-exclamation-circle':type==='info'?'fa-info-circle':'fa-check-circle'}" style="color:${type==='error'?'var(--neon-pink)':type==='info'?'var(--warning)':'var(--success)'};"></i><span>${msg}</span>`;
        setTimeout(() => { toast.style.opacity = '0'; toast.style.transform = 'translateX(-50%) translateY(80px)'; }, 3000);
    }

    function renderTeacherUI() {
        const container = document.getElementById('dashboardContent');
        if (!container) return;

        container.innerHTML = `
            <style>
                .td-sidebar { width:250px; flex-shrink:0; background:rgba(5,5,15,0.9); backdrop-filter:blur(20px); border-left:1px solid var(--border-color); padding:0; position:fixed; inset-block:0; inset-inline-start:0; display:flex; flex-direction:column; z-index:100; overflow-y:auto; }
                .td-sidebar-header { padding:25px 20px; border-bottom:1px solid var(--border-color); text-align:center; }
                .td-sidebar-header .logo-text { font-size:1.2rem; font-weight:900; background:linear-gradient(135deg,var(--neon-blue),var(--neon-violet)); -webkit-background-clip:text; background-clip:text; -webkit-text-fill-color:transparent; display:block; }
                .td-sidebar-header .role-badge { display:inline-block; background:linear-gradient(135deg,var(--neon-violet),var(--neon-pink)); color:white; padding:2px 14px; border-radius:20px; font-size:11px; font-weight:700; margin-top:5px; }
                .td-nav { list-style:none; padding:10px 12px; flex-grow:1; }
                .td-nav-item { margin-bottom:2px; }
                .td-nav-link { display:flex; align-items:center; gap:12px; color:var(--text-secondary); text-decoration:none; padding:10px 16px; border-radius:10px; transition:0.3s; font-weight:600; font-size:0.85rem; cursor:pointer; border:none; background:none; width:100%; text-align:start; font-family:var(--font-main); }
                .td-nav-link:hover { background:var(--glass); color:var(--neon-blue); }
                .td-nav-link.active { background:rgba(0,212,255,0.08); color:var(--neon-blue); border:1px solid rgba(0,212,255,0.1); }
                .td-nav-link i { width:20px; text-align:center; font-size:1rem; }
                .td-nav-link .badge-count { margin-inline-start:auto; background:var(--neon-pink); color:white; font-size:10px; padding:1px 7px; border-radius:10px; font-weight:700; }
                .td-footer { padding:20px; border-top:1px solid var(--border-color); }
                .td-main { margin-inline-start:250px; padding:30px; width:100%; min-height:100vh; }
                .td-top { display:flex; justify-content:space-between; align-items:center; margin-bottom:30px; flex-wrap:wrap; gap:15px; }
                .td-top h1 { font-family:var(--font-heading,'Cairo',sans-serif); font-size:1.5rem; }
                .td-top h1 span { color:var(--neon-blue); }
                .td-page { display:none; }
                .td-page.active { display:block; }
                .td-stats { display:grid; grid-template-columns:repeat(auto-fit,minmax(180px,1fr)); gap:16px; margin-bottom:30px; }
                .td-stat { background:var(--glass,rgba(255,255,255,0.04)); backdrop-filter:blur(12px); padding:22px; border-radius:16px; border:1px solid var(--border-color); transition:0.3s; }
                .td-stat:hover { border-color:var(--neon-blue); transform:translateY(-2px); box-shadow:0 0 20px rgba(0,212,255,0.08); }
                .td-stat .stat-icon { font-size:1.5rem; margin-bottom:8px; }
                .td-stat .stat-num { font-size:1.8rem; font-weight:900; font-family:var(--font-heading,'Cairo',sans-serif); }
                .td-stat .stat-lbl { color:var(--text-secondary); font-size:0.8rem; margin-top:2px; }
                .td-table-wrap { background:rgba(255,255,255,0.02); backdrop-filter:blur(12px); border-radius:16px; border:1px solid var(--border-color); overflow:hidden; overflow-x:auto; }
                .td-table-wrap table { width:100%; border-collapse:collapse; min-width:550px; }
                .td-table-wrap th { padding:14px 18px; text-align:start; font-weight:700; color:var(--neon-blue); font-size:0.8rem; text-transform:uppercase; letter-spacing:0.5px; background:rgba(0,212,255,0.03); border-bottom:1px solid var(--border-color); }
                .td-table-wrap td { padding:12px 18px; border-bottom:1px solid var(--border-color); font-size:0.85rem; }
                .td-table-wrap tr:last-child td { border-bottom:none; }
                .td-table-wrap tr:hover td { background:rgba(255,255,255,0.02); }
                .td-section-title { font-family:var(--font-heading,'Cairo',sans-serif); font-size:1.2rem; margin-bottom:15px; display:flex; align-items:center; gap:10px; }
                .td-section-title i { color:var(--neon-blue); }
                .td-modal-overlay { position:fixed; top:0; left:0; width:100%; height:100%; background:rgba(0,0,0,0.7); backdrop-filter:blur(6px); z-index:1000; display:none; align-items:center; justify-content:center; padding:20px; }
                .td-modal-overlay.active { display:flex; }
                .td-modal { background:#0a0a1a; border:1px solid var(--border-color); border-radius:20px; padding:28px; width:100%; max-width:520px; max-height:90vh; overflow-y:auto; box-shadow:0 25px 60px rgba(0,0,0,0.8); }
                .td-modal-header { display:flex; justify-content:space-between; align-items:center; margin-bottom:22px; }
                .td-modal-header h2 { font-family:var(--font-heading,'Cairo',sans-serif); font-size:1.2rem; }
                .td-modal-close { background:none; border:none; color:var(--text-secondary); font-size:1.5rem; cursor:pointer; transition:0.3s; }
                .td-modal-close:hover { color:var(--neon-pink); }
                .td-form-group { margin-bottom:16px; }
                .td-form-group label { display:block; margin-bottom:5px; font-weight:600; font-size:0.8rem; color:var(--text-secondary); }
                .td-form-group input, .td-form-group select, .td-form-group textarea { width:100%; padding:10px 14px; background:rgba(255,255,255,0.04); border:1px solid var(--border-color); border-radius:10px; color:white; font-family:var(--font-main); font-size:0.9rem; outline:none; transition:0.3s; }
                .td-form-group input:focus, .td-form-group select:focus, .td-form-group textarea:focus { border-color:var(--neon-blue); box-shadow:0 0 12px rgba(0,212,255,0.08); }
                .td-form-group textarea { resize:vertical; min-height:70px; }
                .td-form-group select option { background:#0a0a1a; color:white; }
                .td-form-actions { display:flex; gap:10px; justify-content:flex-end; margin-top:20px; }
                .td-actions-cell { display:flex; gap:6px; flex-wrap:wrap; }
                .td-actions-cell button { padding:5px 10px; border-radius:6px; border:none; cursor:pointer; font-size:11px; font-weight:600; transition:0.3s; font-family:var(--font-main); }
                .td-empty { text-align:center; padding:50px 20px; color:var(--text-secondary); }
                .td-empty i { font-size:2.5rem; margin-bottom:15px; color:var(--text-secondary); }
                .td-badge { display:inline-block; padding:2px 10px; border-radius:20px; font-size:11px; font-weight:700; }
                .td-badge-blue { background:rgba(0,212,255,0.12); color:var(--neon-blue); border:1px solid rgba(0,212,255,0.2); }
                .td-badge-green { background:rgba(0,255,170,0.12); color:var(--success); border:1px solid rgba(0,255,170,0.2); }
                .td-badge-pink { background:rgba(255,51,102,0.12); color:var(--neon-pink); border:1px solid rgba(255,51,102,0.2); }
                .td-badge-yellow { background:rgba(251,191,36,0.12); color:var(--warning); border:1px solid rgba(251,191,36,0.2); }
                .td-badge-violet { background:rgba(168,85,247,0.12); color:var(--neon-violet); border:1px solid rgba(168,85,247,0.2); }
                .td-btn { padding:9px 20px; border-radius:30px; border:none; background:linear-gradient(135deg,var(--neon-blue),var(--neon-violet)); color:white; font-weight:700; cursor:pointer; transition:0.3s; display:inline-flex; align-items:center; gap:7px; text-decoration:none; font-family:var(--font-main); font-size:13px; }
                .td-btn:hover { transform:translateY(-2px); box-shadow:0 8px 20px rgba(0,212,255,0.25); }
                .td-btn-sm { padding:6px 14px; font-size:12px; }
                .td-btn-outline { background:transparent; border:1px solid var(--neon-blue); color:var(--neon-blue); }
                .td-btn-outline:hover { background:var(--neon-blue); color:#000; }
                .td-btn-danger { background:linear-gradient(135deg,var(--neon-pink),#ff6b6b); }
                .td-btn-success { background:linear-gradient(135deg,var(--success),#059669); }
                .td-course-grid { display:grid; grid-template-columns:repeat(auto-fill,minmax(280px,1fr)); gap:20px; }
                .td-course-card { background:rgba(255,255,255,0.02); border:1px solid var(--border-color); border-radius:16px; overflow:hidden; transition:0.3s; }
                .td-course-card:hover { border-color:var(--neon-blue); transform:translateY(-3px); box-shadow:0 0 25px rgba(0,212,255,0.06); }
                .td-course-card img { width:100%; height:160px; object-fit:cover; }
                .td-course-card-body { padding:16px; }
                .td-course-card-body h4 { margin-bottom:8px; font-size:1rem; }
                .td-course-card-body p { color:var(--text-secondary); font-size:0.8rem; margin-bottom:6px; }
                .td-actions-bar { display:flex; justify-content:space-between; align-items:center; margin-bottom:20px; flex-wrap:wrap; gap:12px; }
                .td-sidebar-toggle { display:none; position:fixed; top:12px; inset-inline-start:12px; width:42px; height:42px; background:var(--glass); border:1px solid var(--border-color); border-radius:10px; color:white; font-size:20px; z-index:101; align-items:center; justify-content:center; cursor:pointer; transition:0.3s; background:rgba(16,20,30,0.6); }
                .td-sidebar-toggle:hover { border-color:var(--neon-blue); color:var(--neon-blue); }
                .td-sidebar-overlay { display:none; }
                @media (max-width:992px) {
                    .td-sidebar { width:68px; }
                    .td-sidebar .td-sidebar-header .logo-text, .td-sidebar .td-sidebar-header .role-badge, .td-sidebar .td-nav-link span, .td-sidebar .td-nav-link .badge-count, .td-footer span { display:none; }
                    .td-sidebar .td-nav-link { justify-content:center; padding:10px; }
                    .td-main { margin-inline-start:68px; padding:20px; }
                }
                @media (max-width:768px) {
                    .td-sidebar-toggle { display:flex; }
                    .td-sidebar { width:250px; transform:translateX(100%); inset-inline-start:auto; transition:0.3s cubic-bezier(0.175,0.885,0.32,1.275); z-index:200; }
                    .td-sidebar.open { transform:translateX(0); }
                    .td-sidebar .td-sidebar-header .logo-text, .td-sidebar .td-sidebar-header .role-badge, .td-sidebar .td-nav-link span, .td-sidebar .td-nav-link .badge-count, .td-footer span { display:block; }
                    .td-sidebar .td-nav-link { justify-content:flex-start; padding:10px 16px; }
                    .td-sidebar .td-nav-link i { margin:0 0 0 12px; }
                    .td-sidebar-overlay.open { display:block; position:fixed; inset:0; background:rgba(0,0,0,0.6); z-index:199; backdrop-filter:blur(4px); }
                    .td-main { margin-inline-start:0; padding:16px; padding-top:70px; }
                    .td-stats { grid-template-columns:1fr 1fr; }
                    .td-top { flex-direction:column; align-items:flex-start; }
                }
                @media (max-width:480px) {
                    .td-stats { grid-template-columns:1fr; }
                }
            </style>

            <button class="td-sidebar-toggle" onclick="const s=document.querySelector('.td-sidebar'),o=document.querySelector('.td-sidebar-overlay');s.classList.toggle('open');o.classList.toggle('open');"><i class="fa-solid fa-bars"></i></button>
            <div class="td-sidebar-overlay" onclick="document.querySelector('.td-sidebar').classList.remove('open');this.classList.remove('open');"></div>
            <aside class="td-sidebar">
                <div class="td-sidebar-header">
                    <span class="logo-text">LookaGenius</span>
                    <span class="role-badge"><i class="fa-solid fa-chalkboard-teacher"></i> مدرس</span>
                </div>
                <nav class="td-nav">
                    <div class="td-nav-item"><button class="td-nav-link active" data-tpage="dashboard"><i class="fa-solid fa-gauge"></i> <span>الرئيسية</span></button></div>
                    <div class="td-nav-item"><button class="td-nav-link" data-tpage="courses"><i class="fa-solid fa-graduation-cap"></i> <span>كورساتي</span> <span class="badge-count" id="tdCourseCount">0</span></button></div>
                    <div class="td-nav-item"><button class="td-nav-link" data-tpage="settlements"><i class="fa-solid fa-file-invoice"></i> <span>طلبات التصفية</span></button></div>
                    <div class="td-nav-item"><button class="td-nav-link" data-tpage="articles"><i class="fa-solid fa-newspaper"></i> <span>المقالات</span> <span class="badge-count" id="tdArticleCount">0</span></button></div>
                    <div class="td-nav-item"><button class="td-nav-link" data-tpage="financials"><i class="fa-solid fa-coins"></i> <span>الحسابات المالية</span></button></div>
                    <div class="td-nav-item"><button class="td-nav-link" data-tpage="settings"><i class="fa-solid fa-gear"></i> <span>الإعدادات</span></button></div>
                    <div class="td-nav-item"><a href="index.html" class="td-nav-link"><i class="fa-solid fa-eye"></i> <span>عرض الموقع</span></a></div>
                </nav>
                <div class="td-footer">
                    <button class="td-nav-link" id="tdLogoutBtn" style="color:var(--neon-pink);"><i class="fa-solid fa-right-from-bracket"></i> <span>تسجيل الخروج</span></button>
                </div>
            </aside>

            <main class="td-main">
                <div class="td-top">
                    <h1>مرحباً، <span>${escHtml(teacherName)}</span> 👋</h1>
                    <div style="display:flex;align-items:center;gap:10px;background:var(--glass,rgba(255,255,255,0.04));padding:6px 16px;border-radius:30px;border:1px solid var(--border-color);font-size:0.85rem;">
                        <span style="background:var(--neon-violet);color:white;padding:2px 12px;border-radius:20px;font-size:11px;font-weight:700;">مدرس</span>
                        <i class="fa-solid fa-circle-user" style="font-size:22px;color:var(--neon-blue);"></i>
                    </div>
                </div>

                <section class="td-page active" id="tdPage-dashboard">
                    <div class="td-stats" id="tdStats"></div>
                    <div class="td-section-title"><i class="fa-solid fa-clock-rotate-left"></i> آخر طلبات التصفية</div>
                    <div class="td-table-wrap" id="tdRecentSettlements"></div>
                </section>

                <section class="td-page" id="tdPage-courses">
                    <div class="td-actions-bar">
                        <span style="color:var(--text-secondary);font-size:0.85rem;" id="tdCourseInfo">0 كورس</span>
                        <button class="td-btn" id="tdAddCourseBtn"><i class="fa-solid fa-plus"></i> إضافة كورس</button>
                    </div>
                    <div class="td-course-grid" id="tdCourseGrid"></div>
                    <div class="td-empty" id="tdCourseEmpty" style="display:none;"><i class="fa-solid fa-book"></i><p>لا توجد كورسات مسندة إليك بعد</p></div>
                </section>

                <section class="td-page" id="tdPage-articles">
                    <div class="td-actions-bar">
                        <span style="color:var(--text-secondary);font-size:0.85rem;" id="tdArticleInfo">0 مقال</span>
                        <button class="td-btn" id="tdAddArticleBtn"><i class="fa-solid fa-plus"></i> إضافة مقال</button>
                    </div>
                    <div class="td-table-wrap" id="tdArticleTableWrap">
                        <table>
                            <thead><tr><th>العنوان</th><th>التصنيف</th><th>التاريخ</th><th>الحالة</th><th>إجراءات</th></tr></thead>
                            <tbody id="tdArticleTable"></tbody>
                        </table>
                        <div class="td-empty" id="tdArticleEmpty" style="display:none;"><i class="fa-solid fa-newspaper"></i><p>لا توجد مقالات بعد. انشر أول مقال الآن!</p></div>
                    </div>
                </section>

                <section class="td-page" id="tdPage-settlements">
                    <div class="td-actions-bar">
                        <span style="color:var(--text-secondary);font-size:0.85rem;" id="tdSettlementInfo">0 طلب</span>
                        <button class="td-btn" id="tdNewSettlementBtn"><i class="fa-solid fa-paper-plane"></i> طلب تصفية جديد</button>
                    </div>
                    <div class="td-table-wrap">
                        <table>
                            <thead><tr><th>#</th><th>المبلغ</th><th>الحالة</th><th>التاريخ</th><th>ملاحظات</th></tr></thead>
                            <tbody id="tdSettlementTable"></tbody>
                        </table>
                        <div class="td-empty" id="tdSettlementEmpty" style="display:none;"><i class="fa-solid fa-file-invoice"></i><p>لا توجد طلبات تصفية</p></div>
                    </div>
                </section>

                <section class="td-page" id="tdPage-financials">
                    <div class="td-section-title"><i class="fa-solid fa-coins" style="color:var(--success);"></i> الحسابات المالية</div>
                    <div class="td-stats" id="tdFinStats"></div>
                    <div class="td-table-wrap" style="margin-top:20px;">
                        <table>
                            <thead><tr><th>البيان</th><th>القيمة</th></tr></thead>
                            <tbody id="tdFinTable"></tbody>
                        </table>
                    </div>
                </section>

                <section class="td-page" id="tdPage-settings">
                    <div class="td-table-wrap" style="padding:25px;max-width:600px;">
                        <div class="td-section-title"><i class="fa-solid fa-user"></i> الملف الشخصي</div>
                        <form id="tdProfileForm">
                            <div class="td-form-group"><label>الاسم</label><input type="text" id="tdName" required></div>
                            <div class="td-form-group"><label>البريد الإلكتروني</label><input type="email" id="tdEmail" required></div>
                            <div class="td-form-group"><label>رقم الهاتف</label><input type="text" id="tdPhone" placeholder="اختياري"></div>
                            <button type="submit" class="td-btn"><i class="fa-solid fa-floppy-disk"></i> حفظ التغييرات</button>
                        </form>
                        <hr style="border-color:var(--border-color);margin:30px 0;">
                        <div class="td-section-title"><i class="fa-solid fa-lock" style="color:var(--neon-pink);"></i> تغيير كلمة المرور</div>
                        <form id="tdPasswordForm">
                            <div class="td-form-group"><label>كلمة المرور الحالية</label><input type="password" id="tdCurrentPass" required></div>
                            <div class="td-form-group"><label>كلمة المرور الجديدة</label><input type="password" id="tdNewPass" required minlength="6"></div>
                            <div class="td-form-group"><label>تأكيد كلمة المرور</label><input type="password" id="tdConfirmPass" required></div>
                            <button type="submit" class="td-btn"><i class="fa-solid fa-key"></i> تغيير كلمة المرور</button>
                        </form>
                    </div>
                </section>
            </main>

            <!-- Add Course Modal -->
            <div class="td-modal-overlay" id="tdCourseModal">
                <div class="td-modal">
                    <div class="td-modal-header"><h2>إضافة كورس جديد</h2><button class="td-modal-close" id="tdCourseModalClose">&times;</button></div>
                    <form id="tdCourseForm">
                        <div class="td-form-group"><label>اسم الكورس</label><input type="text" id="tdCourseTitle" required></div>
                        <div class="td-form-group"><label>التصنيف</label>
                            <select id="tdCourseCategory"></select>
                        </div>
                        <div class="td-form-group"><label>المرحلة التعليمية</label>
                            <select id="tdCourseStage">
                                <option value="all">كل المراحل</option><option value="primary">ابتدائي</option>
                                <option value="middle">إعدادي</option><option value="high">ثانوي</option>
                            </select>
                        </div>
                        <div class="td-form-group"><label>السعر</label>
                            <div style="display:flex;gap:8px;">
                                <input type="number" id="tdCoursePrice" required min="0" step="0.01" style="flex:1;">
                                <select id="tdCourseCurrency" style="width:130px;flex-shrink:0;">
                                    <option value="USD">$ دولار</option>
                                    <option value="EGP">ج.م جنيه</option>
                                    <option value="SAR">﷼ ريال</option>
                                    <option value="AED">د.إ درهم</option>
                                    <option value="EUR">€ يورو</option>
                                </select>
                            </div>
                        </div>
                        <div class="td-form-group"><label>المدة</label><input type="text" id="tdCourseDuration" required placeholder="مثال: 30 ساعة"></div>
                        <div class="td-form-group"><label>الوصف</label>
                            <textarea id="tdCourseDesc" required style="min-height:100px;"></textarea>
                            <div style="display:flex;gap:6px;margin-top:6px;flex-wrap:wrap;">
                                <button type="button" class="td-btn td-btn-sm td-btn-outline" onclick="autoGenerateDesc()"><i class="fa-solid fa-wand-magic-sparkles"></i> قالب سريع</button>
                                <button type="button" class="td-btn td-btn-sm td-btn-outline" onclick="generateAIDesc()" style="border-color:var(--neon-violet);color:var(--neon-violet);"><i class="fa-solid fa-robot"></i> توليد بـ AI</button>
                            </div>
                        </div>
                        <div class="td-form-group"><label>رابط الصورة</label><input type="url" id="tdCourseImage" placeholder="اختياري" value="https://picsum.photos/seed/course/400/250"></div>
                        <div class="td-form-actions">
                            <button type="button" class="td-btn td-btn-outline" id="tdCourseModalCancel">إلغاء</button>
                            <button type="submit" class="td-btn">نشر الكورس</button>
                        </div>
                    </form>
                </div>
            </div>

            <!-- Add Article Modal -->
            <div class="td-modal-overlay" id="tdArticleModal">
                <div class="td-modal" style="max-width:650px;">
                    <div class="td-modal-header"><h2>إضافة مقال جديد</h2><button class="td-modal-close" id="tdArticleModalClose">&times;</button></div>
                    <form id="tdArticleForm">
                        <input type="hidden" id="tdArticleId">
                        <div class="td-form-group"><label>عنوان المقال</label>
                            <input type="text" id="tdArticleTitle" required>
                            <button type="button" class="td-btn td-btn-sm td-btn-outline" onclick="generateTeacherArticleAI()" style="margin-top:6px;"><i class="fa-solid fa-robot"></i> توليد بـ AI</button>
                        </div>
                        <div class="td-form-group"><label>النص القصير (excerpt)</label><textarea id="tdArticleExcerpt" required rows="2"></textarea></div>
                        <div class="td-form-group"><label>المحتوى الكامل</label>
                            <textarea id="tdArticleContent" required style="min-height:200px;font-family:monospace;direction:ltr;text-align:left;"></textarea>
                            <div class="input-hint" style="font-size:0.75rem;color:var(--text-secondary);margin-top:3px;">يمكنك استخدام وسوم HTML (h2, p, ul, li, strong, em)</div>
                        </div>
                        <div class="td-form-group"><label>التصنيف</label>
                            <select id="tdArticleCategory">
                                <option value="education">تعليم</option><option value="tech">تكنولوجيا</option>
                                <option value="scholarships">منح</option><option value="career">تطوير مهني</option><option value="general">عام</option>
                            </select>
                        </div>
                        <div class="td-form-group"><label>صورة المقال</label><input type="url" id="tdArticleImage" placeholder="رابط الصورة (اختياري)"></div>
                        <div class="td-form-actions">
                            <button type="button" class="td-btn td-btn-outline" id="tdArticleModalCancel">إلغاء</button>
                            <button type="button" class="td-btn td-btn-success" onclick="generateTeacherArticleAI()" style="background:linear-gradient(135deg,var(--neon-violet),var(--neon-pink));font-size:12px;"><i class="fa-solid fa-robot"></i> AI</button>
                            <button type="submit" class="td-btn">نشر المقال</button>
                        </div>
                    </form>
                </div>
            </div>

            <!-- Content Management Modal (Modules + Lessons) -->
            <div class="td-modal-overlay" id="tdLessonModal">
                <div class="td-modal" style="max-width:800px;">
                    <div class="td-modal-header">
                        <h2><i class="fa-solid fa-layer-group"></i> إدارة المحتوى: <span id="tdLessonCourseName" style="color:var(--neon-blue);font-size:1rem;"></span></h2>
                        <button class="td-modal-close" id="tdLessonModalClose">&times;</button>
                    </div>
                    <!-- Modules & Lessons List -->
                    <div id="tdModuleList" style="margin-bottom:20px;"></div>
                    <!-- Add Module Button -->
                    <div style="text-align:center;margin-bottom:20px;">
                        <button class="td-btn td-btn-sm td-btn-outline" id="tdAddModuleBtn" style="border-color:var(--success);color:var(--success);"><i class="fa-solid fa-plus"></i> إضافة وحدة جديدة</button>
                    </div>
                    <hr style="border-color:var(--border-color);margin:20px 0;">
                    <!-- Add/Edit Lesson Form -->
                    <div class="td-section-title" style="font-size:1rem;"><i class="fa-solid fa-plus-circle" style="color:var(--success);"></i> <span id="tdLessonFormTitle">إضافة درس جديد</span></div>
                    <form id="tdLessonForm">
                        <input type="hidden" id="tdLessonCourseId">
                        <input type="hidden" id="tdLessonEditId">
                        <input type="hidden" id="tdLessonEditModuleId">
                        <div class="td-form-group"><label>الوحدة</label>
                            <select id="tdLessonModuleSelect" required></select>
                        </div>
                        <div class="td-form-group"><label>عنوان الدرس</label><input type="text" id="tdLessonTitle" required></div>
                        <div class="td-form-group"><label>رابط فيديو يوتيوب</label>
                            <input type="url" id="tdLessonVideo" required placeholder="https://youtu.be/xxx أو https://www.youtube.com/watch?v=xxx">
                            <div class="input-hint" style="font-size:0.75rem;color:var(--text-secondary);margin-top:3px;">يمكنك استخدام روابط يوتيوب العادية أو المختصرة، سيتم تحويلها تلقائياً</div>
                        </div>
                        <div class="td-form-group" style="display:grid;grid-template-columns:1fr 1fr;gap:15px;">
                            <div><label>المدة</label><input type="text" id="tdLessonDuration" placeholder="مثال: 15:30"></div>
                            <div><label style="display:flex;align-items:center;gap:8px;height:100%;padding-top:20px;">
                                <input type="checkbox" id="tdLessonFree" style="accent-color:var(--success);width:auto;">
                                درس مجاني (معاينة)
                            </label></div>
                        </div>
                        <div class="td-form-actions">
                            <button type="button" class="td-btn td-btn-outline" id="tdLessonCancel">إلغاء</button>
                            <button type="submit" class="td-btn"><i class="fa-solid fa-save"></i> حفظ الدرس</button>
                        </div>
                    </form>
                    <div style="margin-top:15px;padding:15px;background:rgba(0,212,255,0.04);border-radius:12px;border:1px solid rgba(0,212,255,0.1);font-size:0.8rem;color:var(--text-secondary);">
                        <i class="fa-solid fa-lightbulb" style="color:var(--warning);"></i>
                        نصائح: استخدم فيديوهات يوتيوب غير مدرجة (Unlisted) للخصوصية. يفضل رفع الفيديوهات بجودة 1080p وبحجم شاشة 16:9.
                    </div>
                </div>
            </div>

            <!-- New Settlement Modal -->
            <div class="td-modal-overlay" id="tdSettlementModal">
                <div class="td-modal">
                    <div class="td-modal-header"><h2>طلب تصفية حساب</h2><button class="td-modal-close" id="tdSettlementModalClose">&times;</button></div>
                    <form id="tdSettlementForm">
                        <div class="td-form-group"><label>المبلغ ($)</label><input type="number" id="tdSettlementAmount" required min="1" step="0.01"></div>
                        <div class="td-form-group"><label>ملاحظات</label><textarea id="tdSettlementNotes" placeholder="اختياري" rows="3"></textarea></div>
                        <div class="td-form-actions">
                            <button type="button" class="td-btn td-btn-outline" id="tdSettlementCancel">إلغاء</button>
                            <button type="submit" class="td-btn">إرسال الطلب</button>
                        </div>
                    </form>
                </div>
            </div>
        `;

        setupNavigation();
        setupModals();
        setupForms();
        renderAll();
    }

    function setupNavigation() {
        document.querySelectorAll('[data-tpage]').forEach(btn => {
            btn.addEventListener('click', () => {
                document.querySelectorAll('[data-tpage]').forEach(b => b.classList.remove('active'));
                btn.classList.add('active');
                document.querySelectorAll('.td-page').forEach(s => s.classList.remove('active'));
                const page = document.getElementById('tdPage-' + btn.dataset.tpage);
                if (page) page.classList.add('active');
                currentPage = btn.dataset.tpage;
                if (currentPage === 'dashboard') renderDashboard();
                if (currentPage === 'courses') renderCourses();
                if (currentPage === 'settlements') renderSettlements();
                if (currentPage === 'financials') renderFinancials();
                if (currentPage === 'articles') renderArticles();
            });
        });
        document.getElementById('tdLogoutBtn').addEventListener('click', () => { if (window.auth) window.auth.logout(); });
    }

    function setupModals() {
        // Course modal
        function populateTeacherCourseCategories() {
            const sel = document.getElementById('tdCourseCategory');
            let cats = window.db.getCourseCategories();
            if (!cats || cats.length === 0) {
                const defaults = [
                    { id: 'languages', name: 'لغات' }, { id: 'science', name: 'علوم' },
                    { id: 'math', name: 'رياضيات' }, { id: 'tech', name: 'تكنولوجيا' }
                ];
                defaults.forEach(d => window.db.addCourseCategory(d));
                cats = window.db.getCourseCategories();
            }
            sel.innerHTML = cats.map(c => `<option value="${c.id}">${escHtml(c.name)}</option>`).join('');
        }

        const courseModal = document.getElementById('tdCourseModal');
        document.getElementById('tdAddCourseBtn').addEventListener('click', () => {
            populateTeacherCourseCategories();
            courseModal.classList.add('active');
        });
        document.getElementById('tdCourseModalClose').addEventListener('click', () => courseModal.classList.remove('active'));
        document.getElementById('tdCourseModalCancel').addEventListener('click', () => courseModal.classList.remove('active'));
        courseModal.addEventListener('click', e => { if (e.target === e.currentTarget) courseModal.classList.remove('active'); });

        // Lesson modal
        const lessonModal = document.getElementById('tdLessonModal');
        document.getElementById('tdLessonModalClose').addEventListener('click', () => { lessonModal.classList.remove('active'); document.getElementById('tdLessonForm').reset(); document.getElementById('tdLessonEditId').value = ''; document.getElementById('tdLessonEditModuleId').value = ''; });
        document.getElementById('tdLessonCancel').addEventListener('click', () => { lessonModal.classList.remove('active'); document.getElementById('tdLessonForm').reset(); document.getElementById('tdLessonEditId').value = ''; document.getElementById('tdLessonEditModuleId').value = ''; });
        lessonModal.addEventListener('click', e => { if (e.target === e.currentTarget) { lessonModal.classList.remove('active'); document.getElementById('tdLessonForm').reset(); document.getElementById('tdLessonEditId').value = ''; document.getElementById('tdLessonEditModuleId').value = ''; } });
        // Add module button
        document.getElementById('tdAddModuleBtn').addEventListener('click', () => {
            const courseId = parseInt(document.getElementById('tdLessonCourseId').value);
            if (!courseId) return;
            window.addModule(courseId);
        });

        // Settlement modal
        const settlementModal = document.getElementById('tdSettlementModal');
        document.getElementById('tdNewSettlementBtn').addEventListener('click', () => settlementModal.classList.add('active'));
        document.getElementById('tdSettlementModalClose').addEventListener('click', () => settlementModal.classList.remove('active'));
        document.getElementById('tdSettlementCancel').addEventListener('click', () => settlementModal.classList.remove('active'));
        settlementModal.addEventListener('click', e => { if (e.target === e.currentTarget) settlementModal.classList.remove('active'); });

        // Article modal
        const articleModal = document.getElementById('tdArticleModal');
        document.getElementById('tdAddArticleBtn').addEventListener('click', () => {
            document.getElementById('tdArticleId').value = '';
            document.getElementById('tdArticleForm').reset();
            articleModal.classList.add('active');
        });
        document.getElementById('tdArticleModalClose').addEventListener('click', () => { articleModal.classList.remove('active'); document.getElementById('tdArticleForm').reset(); });
        document.getElementById('tdArticleModalCancel').addEventListener('click', () => { articleModal.classList.remove('active'); document.getElementById('tdArticleForm').reset(); });
        articleModal.addEventListener('click', e => { if (e.target === e.currentTarget) { articleModal.classList.remove('active'); document.getElementById('tdArticleForm').reset(); } });
    }

    // Global content manager functions
    window.openLessonManager = function(courseId, courseTitle) {
        const modal = document.getElementById('tdLessonModal');
        document.getElementById('tdLessonCourseId').value = courseId;
        document.getElementById('tdLessonCourseName').textContent = courseTitle;
        document.getElementById('tdLessonEditId').value = '';
        document.getElementById('tdLessonEditModuleId').value = '';
        document.getElementById('tdLessonForm').reset();
        populateModuleSelect(courseId);
        renderModuleList(courseId);
        document.getElementById('tdLessonFormTitle').textContent = 'إضافة درس جديد';
        modal.classList.add('active');
    };

    window.editLesson = function(courseId, lessonId, moduleId) {
        const course = window.db.getCourses().find(c => c.id === courseId);
        if (!course) return;
        let lesson = null;
        if (course.modules && course.modules.length > 0) {
            for (const mod of course.modules) {
                if (mod.lessons) {
                    lesson = mod.lessons.find(l => l.id === lessonId);
                    if (lesson) break;
                }
            }
        }
        if (!lesson && course.lessons) lesson = course.lessons.find(l => l.id === lessonId);
        if (!lesson) return;
        document.getElementById('tdLessonEditId').value = lessonId;
        document.getElementById('tdLessonEditModuleId').value = moduleId || '';
        document.getElementById('tdLessonTitle').value = lesson.title;
        document.getElementById('tdLessonVideo').value = lesson.videoURL || '';
        document.getElementById('tdLessonDuration').value = lesson.duration || '';
        document.getElementById('tdLessonFree').checked = lesson.isFree || false;
        if (moduleId && document.getElementById('tdLessonModuleSelect')) {
            document.getElementById('tdLessonModuleSelect').value = moduleId;
        }
        document.getElementById('tdLessonFormTitle').textContent = 'تعديل الدرس';
    };

    window.deleteLesson = function(courseId, lessonId) {
        if (!confirm('هل أنت متأكد من حذف هذا الدرس؟')) return;
        window.db.deleteLesson(courseId, lessonId);
        const course = window.db.getCourses().find(c => c.id === courseId);
        renderModuleList(courseId);
        populateModuleSelect(courseId);
        showToast('تم حذف الدرس ✅');
    };

    window.addModule = function(courseId) {
        const title = prompt('أدخل اسم الوحدة الجديدة:');
        if (!title || !title.trim()) return;
        window.db.addModule(courseId, { title: title.trim() });
        renderModuleList(courseId);
        populateModuleSelect(courseId);
        showToast('تم إضافة الوحدة ✅');
    };

    window.editModule = function(courseId, moduleId) {
        const modules = window.db.getCourseModules(courseId);
        const mod = modules.find(m => m.id === moduleId);
        if (!mod) return;
        const title = prompt('تعديل اسم الوحدة:', mod.title);
        if (!title || !title.trim()) return;
        window.db.updateModule(courseId, moduleId, { title: title.trim() });
        renderModuleList(courseId);
        populateModuleSelect(courseId);
        showToast('تم تعديل الوحدة ✅');
    };

    window.deleteModule = function(courseId, moduleId) {
        if (!confirm('هل أنت متأكد من حذف هذه الوحدة مع جميع دروسها؟')) return;
        window.db.deleteModule(courseId, moduleId);
        renderModuleList(courseId);
        populateModuleSelect(courseId);
        showToast('تم حذف الوحدة ✅');
    };

    window.moveLessonUp = function(courseId, moduleId, lessonId) {
        const modules = window.db.getCourseModules(courseId);
        const mod = modules.find(m => m.id === moduleId);
        if (!mod || !mod.lessons) return;
        const idx = mod.lessons.findIndex(l => l.id === lessonId);
        if (idx <= 0) return;
        [mod.lessons[idx], mod.lessons[idx - 1]] = [mod.lessons[idx - 1], mod.lessons[idx]];
        const data = window.db.getData();
        window.db.saveData(data);
        renderModuleList(courseId);
    };

    window.moveLessonDown = function(courseId, moduleId, lessonId) {
        const modules = window.db.getCourseModules(courseId);
        const mod = modules.find(m => m.id === moduleId);
        if (!mod || !mod.lessons) return;
        const idx = mod.lessons.findIndex(l => l.id === lessonId);
        if (idx === -1 || idx >= mod.lessons.length - 1) return;
        [mod.lessons[idx], mod.lessons[idx + 1]] = [mod.lessons[idx + 1], mod.lessons[idx]];
        const data = window.db.getData();
        window.db.saveData(data);
        renderModuleList(courseId);
    };

    window.moveModuleUp = function(courseId, moduleId) {
        const data = window.db.getData();
        const course = data.courses.find(c => c.id === courseId);
        if (!course || !course.modules) return;
        const idx = course.modules.findIndex(m => m.id === moduleId);
        if (idx <= 0) return;
        [course.modules[idx], course.modules[idx - 1]] = [course.modules[idx - 1], course.modules[idx]];
        course.modules.forEach((m, i) => m.order = i);
        window.db.saveData(data);
        renderModuleList(courseId);
    };

    window.moveModuleDown = function(courseId, moduleId) {
        const data = window.db.getData();
        const course = data.courses.find(c => c.id === courseId);
        if (!course || !course.modules) return;
        const idx = course.modules.findIndex(m => m.id === moduleId);
        if (idx === -1 || idx >= course.modules.length - 1) return;
        [course.modules[idx], course.modules[idx + 1]] = [course.modules[idx + 1], course.modules[idx]];
        course.modules.forEach((m, i) => m.order = i);
        window.db.saveData(data);
        renderModuleList(courseId);
    };

    function populateModuleSelect(courseId) {
        const sel = document.getElementById('tdLessonModuleSelect');
        if (!sel) return;
        const modules = window.db.getCourseModules(courseId);
        if (modules.length === 0) {
            sel.innerHTML = '<option value="">— لا توجد وحدات —</option>';
            return;
        }
        sel.innerHTML = modules.map(m => `<option value="${m.id}">${escHtml(m.title)}</option>`).join('');
    }

    function renderModuleList(courseId) {
        const course = window.db.getCourses().find(c => c.id === courseId);
        const container = document.getElementById('tdModuleList');
        if (!course) { container.innerHTML = ''; return; }
        const modules = window.db.getCourseModules(courseId);
        if (modules.length === 0) {
            container.innerHTML = '<div class="td-empty" style="padding:30px 20px;"><i class="fa-solid fa-layer-group"></i><p>لا توجد وحدات بعد. أضف أول وحدة الآن!</p></div>';
            return;
        }
        container.innerHTML = modules.map((mod, mi) => {
            const lessons = mod.lessons || [];
            const lsHtml = lessons.length === 0
                ? '<div style="padding:10px 20px;color:var(--text-secondary);font-size:0.8rem;">لا توجد دروس في هذه الوحدة</div>'
                : lessons.map((l, li) => {
                    return `
                    <div style="display:flex;align-items:center;gap:8px;padding:8px 12px;background:rgba(255,255,255,0.02);border:1px solid var(--border-color);border-radius:8px;margin-bottom:4px;">
                        <div style="display:flex;gap:2px;flex-direction:column;">
                            <button class="td-btn td-btn-sm" style="padding:2px 6px;font-size:9px;background:none;border:1px solid var(--border-color);color:var(--text-secondary);border-radius:4px;cursor:pointer;" onclick="moveLessonUp(${courseId},${mod.id},${l.id})" title="تحريك لأعلى"><i class="fa-solid fa-chevron-up"></i></button>
                            <button class="td-btn td-btn-sm" style="padding:2px 6px;font-size:9px;background:none;border:1px solid var(--border-color);color:var(--text-secondary);border-radius:4px;cursor:pointer;" onclick="moveLessonDown(${courseId},${mod.id},${l.id})" title="تحريك لأسفل"><i class="fa-solid fa-chevron-down"></i></button>
                        </div>
                        <span style="background:var(--neon-blue);color:#000;width:22px;height:22px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:10px;font-weight:900;flex-shrink:0;">${li+1}</span>
                        <div style="flex:1;min-width:100px;">
                            <strong style="font-size:0.85rem;">${escHtml(l.title)}</strong>
                            <div style="font-size:0.7rem;color:var(--text-secondary);">
                                <i class="fa-regular fa-clock"></i> ${escHtml(l.duration || '—')}
                                ${l.isFree ? ' <span class="td-badge td-badge-green" style="font-size:8px;">مجاني</span>' : ''}
                            </div>
                        </div>
                        <div style="display:flex;gap:4px;">
                            <button class="td-btn td-btn-sm td-btn-outline" style="padding:4px 8px;font-size:10px;" onclick="editLesson(${courseId},${l.id},${mod.id})"><i class="fa-solid fa-pen"></i></button>
                            <button class="td-btn td-btn-sm td-btn-danger" style="padding:4px 8px;font-size:10px;" onclick="deleteLesson(${courseId},${l.id})"><i class="fa-solid fa-trash"></i></button>
                        </div>
                    </div>`;
                }).join('');

            return `
            <div style="margin-bottom:12px;background:rgba(255,255,255,0.015);border:1px solid var(--border-color);border-radius:14px;overflow:hidden;">
                <div style="display:flex;align-items:center;gap:8px;padding:12px 16px;background:rgba(0,212,255,0.03);border-bottom:1px solid var(--border-color);flex-wrap:wrap;">
                    <div style="display:flex;gap:2px;flex-direction:column;">
                        <button class="td-btn td-btn-sm" style="padding:2px 6px;font-size:9px;background:none;border:1px solid var(--border-color);color:var(--text-secondary);border-radius:4px;cursor:pointer;" onclick="moveModuleUp(${courseId},${mod.id})" title="تحريك الوحدة لأعلى"><i class="fa-solid fa-chevron-up"></i></button>
                        <button class="td-btn td-btn-sm" style="padding:2px 6px;font-size:9px;background:none;border:1px solid var(--border-color);color:var(--text-secondary);border-radius:4px;cursor:pointer;" onclick="moveModuleDown(${courseId},${mod.id})" title="تحريك الوحدة لأسفل"><i class="fa-solid fa-chevron-down"></i></button>
                    </div>
                    <span style="background:var(--neon-violet);color:white;width:26px;height:26px;border-radius:8px;display:flex;align-items:center;justify-content:center;font-size:12px;font-weight:900;flex-shrink:0;">${mi+1}</span>
                    <strong style="flex:1;font-size:0.95rem;">${escHtml(mod.title)}</strong>
                    <span style="font-size:0.75rem;color:var(--text-secondary);"><i class="fa-solid fa-video"></i> ${lessons.length} درس</span>
                    <div style="display:flex;gap:4px;">
                        <button class="td-btn td-btn-sm td-btn-outline" style="padding:4px 10px;font-size:10px;border-color:var(--neon-violet);color:var(--neon-violet);" onclick="editModule(${courseId},${mod.id})"><i class="fa-solid fa-pen"></i></button>
                        <button class="td-btn td-btn-sm td-btn-danger" style="padding:4px 10px;font-size:10px;" onclick="deleteModule(${courseId},${mod.id})"><i class="fa-solid fa-trash"></i></button>
                    </div>
                </div>
                <div style="padding:8px 12px;">
                    ${lsHtml}
                </div>
            </div>`;
        }).join('');
    }

    function setupForms() {
        // Add Course form
        document.getElementById('tdCourseForm').addEventListener('submit', (e) => {
            e.preventDefault();
            const data = {
                title: document.getElementById('tdCourseTitle').value.trim(),
                category: document.getElementById('tdCourseCategory').value,
                stage: document.getElementById('tdCourseStage').value,
                price: parseFloat(document.getElementById('tdCoursePrice').value) || 0,
                currency: document.getElementById('tdCourseCurrency').value,
                duration: document.getElementById('tdCourseDuration').value.trim(),
                description: document.getElementById('tdCourseDesc').value.trim(),
                image: document.getElementById('tdCourseImage').value.trim() || 'https://picsum.photos/seed/'+Date.now()+'/400/250',
                badge: document.getElementById('tdCourseTitle').value.trim().split(' ').slice(0,2).join(' '),
                teacherIds: [teacherId]
            };
            window.db.addCourse(data);
            // Initialize financial record if not exists
            const financials = window.db.getFinancials();
            if (!financials.find(f => f.teacherId === teacherId)) {
                const data2 = window.db.getData();
                data2.financials.push({ id: Date.now(), teacherId, totalEarned: 0, paid: 0, pending: 0, lastUpdated: new Date().toISOString() });
                window.db.saveData(data2);
            }
            showToast('تم إضافة الكورس بنجاح ✅');
            document.getElementById('tdCourseModal').classList.remove('active');
            document.getElementById('tdCourseForm').reset();
            renderAll();
        });

        // Settlement form
        document.getElementById('tdSettlementForm').addEventListener('submit', (e) => {
            e.preventDefault();
            const amount = parseFloat(document.getElementById('tdSettlementAmount').value);
            const notes = document.getElementById('tdSettlementNotes').value.trim();
            window.db.addSettlementRequest({
                teacherId,
                teacherName,
                amount,
                notes
            });
            showToast('تم إرسال طلب التصفية بنجاح ✅');
            document.getElementById('tdSettlementModal').classList.remove('active');
            document.getElementById('tdSettlementForm').reset();
            renderAll();
        });

        // Lesson form
        document.getElementById('tdLessonForm').addEventListener('submit', (e) => {
            e.preventDefault();
            const courseId = parseInt(document.getElementById('tdLessonCourseId').value);
            const lessonId = document.getElementById('tdLessonEditId').value;
            const editModId = document.getElementById('tdLessonEditModuleId').value;
            const moduleId = document.getElementById('tdLessonModuleSelect').value;
            const videoUrl = document.getElementById('tdLessonVideo').value.trim();
            const data = {
                title: document.getElementById('tdLessonTitle').value.trim(),
                videoURL: videoUrl,
                videoEmbed: getYouTubeEmbedUrl(videoUrl),
                duration: document.getElementById('tdLessonDuration').value.trim(),
                isFree: document.getElementById('tdLessonFree').checked
            };
            if (lessonId) {
                window.db.updateLesson(courseId, lessonId, data, editModId || moduleId);
                showToast('تم تحديث الدرس ✅');
            } else {
                window.db.addLesson(courseId, data, moduleId);
                showToast('تم إضافة الدرس ✅');
            }
            document.getElementById('tdLessonForm').reset();
            document.getElementById('tdLessonEditId').value = '';
            document.getElementById('tdLessonEditModuleId').value = '';
            document.getElementById('tdLessonFormTitle').textContent = 'إضافة درس جديد';
            renderModuleList(courseId);
            populateModuleSelect(courseId);
        });

        // Article form
        document.getElementById('tdArticleForm').addEventListener('submit', (e) => {
            e.preventDefault();
            const id = document.getElementById('tdArticleId').value;
            const data = {
                title: document.getElementById('tdArticleTitle').value.trim(),
                excerpt: document.getElementById('tdArticleExcerpt').value.trim(),
                content: document.getElementById('tdArticleContent').value.trim(),
                category: document.getElementById('tdArticleCategory').value,
                image: document.getElementById('tdArticleImage').value.trim() || '',
                author: teacherName,
                authorType: 'team'
            };
            if (id) {
                window.db.updateArticle(id, data);
                showToast('تم تحديث المقال ✅');
            } else {
                window.db.addArticle(data);
                showToast('تم نشر المقال بنجاح ✅');
            }
            document.getElementById('tdArticleModal').classList.remove('active');
            document.getElementById('tdArticleForm').reset();
            renderArticles();
        });

        // Profile form
        document.getElementById('tdProfileForm').addEventListener('submit', (e) => {
            e.preventDefault();
            window.db.updateUser(teacherId, {
                name: document.getElementById('tdName').value.trim(),
                email: document.getElementById('tdEmail').value.trim(),
                phone: document.getElementById('tdPhone').value.trim()
            });
            showToast('تم تحديث الملف الشخصي ✅');
        });

        // Password form
        document.getElementById('tdPasswordForm').addEventListener('submit', (e) => {
            e.preventDefault();
            const current = document.getElementById('tdCurrentPass').value;
            const newPass = document.getElementById('tdNewPass').value;
            const confirm = document.getElementById('tdConfirmPass').value;
            if (newPass !== confirm) { showToast('كلمة المرور الجديدة غير متطابقة ❌', 'error'); return; }
            const users = window.db.getUsers();
            const user = users.find(u => u.id === teacherId);
            if (!user || user.password !== current) { showToast('كلمة المرور الحالية غير صحيحة ❌', 'error'); return; }
            window.db.updateUser(teacherId, { password: newPass });
            showToast('تم تغيير كلمة المرور بنجاح ✅');
            document.getElementById('tdPasswordForm').reset();
        });
    }

    function renderAll() {
        document.getElementById('tdCourseCount').textContent = window.db.getCourses().filter(c => (c.teacherIds || []).includes(teacherId)).length;
        renderDashboard();
        renderCourses();
        renderArticles();
        renderSettlements();
        renderFinancials();
        // Fill profile form
        const user = window.auth.currentUser;
        document.getElementById('tdName').value = user.name || '';
        document.getElementById('tdEmail').value = user.email || '';
        document.getElementById('tdPhone').value = user.phone || '';
    }

    function renderDashboard() {
        const courses = window.db.getCourses().filter(c => (c.teacherIds || []).includes(teacherId));
        const financials = window.db.getFinancials();
        const fin = financials.find(f => f.teacherId === teacherId) || { totalEarned: 0, paid: 0, pending: 0 };
        const settlements = window.db.getSettlementRequests().filter(r => r.teacherId === teacherId);
        const pendingSettlements = settlements.filter(r => r.status === 'pending').length;

        document.getElementById('tdStats').innerHTML = `
            <div class="td-stat"><div class="stat-icon" style="color:var(--neon-blue);"><i class="fa-solid fa-graduation-cap"></i></div><div class="stat-num">${courses.length}</div><div class="stat-lbl">كورساتي</div></div>
            <div class="td-stat"><div class="stat-icon" style="color:var(--success);"><i class="fa-solid fa-dollar-sign"></i></div><div class="stat-num">$${fin.totalEarned || 0}</div><div class="stat-lbl">إجمالي الأرباح</div></div>
            <div class="td-stat"><div class="stat-icon" style="color:var(--neon-violet);"><i class="fa-solid fa-file-invoice"></i></div><div class="stat-num">${pendingSettlements}</div><div class="stat-lbl">طلبات معلقة</div></div>
            <div class="td-stat"><div class="stat-icon" style="color:var(--warning);"><i class="fa-solid fa-clock"></i></div><div class="stat-num">$${fin.pending || 0}</div><div class="stat-lbl">المبلغ المعلق</div></div>
        `;

        // Recent settlements
        const recent = [...settlements].sort((a,b) => new Date(b.createdAt||0) - new Date(a.createdAt||0)).slice(0,5);
        const wrap = document.getElementById('tdRecentSettlements');
        if (recent.length === 0) {
            wrap.innerHTML = '<div class="td-empty"><i class="fa-solid fa-file-invoice"></i><p>لا توجد طلبات تصفية بعد</p></div>';
            return;
        }
        wrap.innerHTML = `
            <table>
                <thead><tr><th>#</th><th>المبلغ</th><th>الحالة</th><th>التاريخ</th></tr></thead>
                <tbody>${recent.map((r,i) => {
                    const st = r.status === 'pending' ? 'td-badge-yellow' : r.status === 'approved' ? 'td-badge-green' : 'td-badge-pink';
                    const stText = r.status === 'pending' ? 'قيد الانتظار' : r.status === 'approved' ? 'تمت الموافقة' : 'مرفوض';
                    return `<tr><td>${i+1}</td><td style="color:var(--success);font-weight:700;">$${r.amount}</td><td><span class="td-badge ${st}">${stText}</span></td><td style="color:var(--text-secondary);font-size:0.8rem;">${formatDate(r.createdAt)}</td></tr>`;
                }).join('')}</tbody>
            </table>
        `;
    }

    function renderCourses() {
        const courses = window.db.getCourses().filter(c => (c.teacherIds || []).includes(teacherId));
        document.getElementById('tdCourseInfo').textContent = courses.length + ' كورس';
        const grid = document.getElementById('tdCourseGrid');
        const empty = document.getElementById('tdCourseEmpty');
        if (courses.length === 0) { grid.innerHTML = ''; empty.style.display = 'block'; return; }
        empty.style.display = 'none';
        grid.innerHTML = courses.map(c => {
            const modules = window.db.getCourseModules(c.id);
            const modCount = modules.length;
            const lessonCount = window.db.getCourseLessons(c.id).length;
            return `
            <div class="td-course-card">
                <img src="${escHtml(c.image)}" onerror="this.src='https://picsum.photos/seed/${c.id}/400/250'" alt="${escHtml(c.title)}">
                <div class="td-course-card-body">
                    <h4>${escHtml(c.title)}</h4>
                    <p><i class="fa-solid fa-tag" style="color:var(--neon-blue);"></i> ${escHtml(c.category)} | <i class="fa-solid fa-layer-group" style="color:var(--neon-violet);"></i> ${c.stage === 'primary' ? 'ابتدائي' : c.stage === 'middle' ? 'إعدادي' : c.stage === 'high' ? 'ثانوي' : 'كل المراحل'}</p>
                    <p><i class="fa-regular fa-clock" style="color:var(--text-secondary);"></i> ${escHtml(c.duration)} | <span style="color:var(--success);font-weight:700;">${getCurrencySymbol(c.currency||'USD')}${c.price}</span> | <i class="fa-solid fa-layer-group" style="color:var(--neon-violet);"></i> ${modCount} وحدة | <i class="fa-solid fa-video" style="color:var(--neon-blue);"></i> ${lessonCount} درس</p>
                    <p style="font-size:0.75rem;color:var(--text-secondary);">${escHtml(c.description).substring(0,80)}${c.description.length > 80 ? '...' : ''}</p>
                    <div style="display:flex;gap:8px;margin-top:12px;flex-wrap:wrap;">
                        <button class="td-btn td-btn-sm" onclick="openLessonManager(${c.id},'${escHtml(c.title)}')"><i class="fa-solid fa-video"></i> إدارة المحتوى</button>
                        <a href="course-view.html?id=${c.id}" target="_blank" class="td-btn td-btn-sm td-btn-outline"><i class="fa-solid fa-eye"></i> عرض الكورس</a>
                    </div>
                </div>
            </div>`;
        }).join('');
    }

    function renderSettlements() {
        const settlements = window.db.getSettlementRequests().filter(r => r.teacherId === teacherId);
        document.getElementById('tdSettlementInfo').textContent = settlements.length + ' طلب';
        const tbody = document.getElementById('tdSettlementTable');
        const empty = document.getElementById('tdSettlementEmpty');
        if (settlements.length === 0) { tbody.innerHTML = ''; empty.style.display = 'block'; return; }
        empty.style.display = 'none';
        tbody.innerHTML = [...settlements].sort((a,b) => new Date(b.createdAt||0) - new Date(a.createdAt||0)).map((r,i) => {
            const st = r.status === 'pending' ? 'td-badge-yellow' : r.status === 'approved' ? 'td-badge-green' : 'td-badge-pink';
            const stText = r.status === 'pending' ? 'قيد الانتظار' : r.status === 'approved' ? '✅ تمت الموافقة' : '❌ مرفوض';
            return `<tr><td>${i+1}</td><td style="color:var(--success);font-weight:700;">$${r.amount}</td><td><span class="td-badge ${st}">${stText}</span></td><td style="color:var(--text-secondary);font-size:0.8rem;">${formatDate(r.createdAt)}</td><td style="color:var(--text-secondary);font-size:0.8rem;">${escHtml(r.notes || '-')}</td></tr>`;
        }).join('');
    }

    function renderFinancials() {
        const financials = window.db.getFinancials();
        const fin = financials.find(f => f.teacherId === teacherId) || { totalEarned: 0, paid: 0, pending: 0 };
        document.getElementById('tdFinStats').innerHTML = `
            <div class="td-stat"><div class="stat-icon" style="color:var(--success);"><i class="fa-solid fa-coins"></i></div><div class="stat-num">$${fin.totalEarned || 0}</div><div class="stat-lbl">الإجمالي المكتسب</div></div>
            <div class="td-stat"><div class="stat-icon" style="color:var(--neon-blue);"><i class="fa-solid fa-check-circle"></i></div><div class="stat-num">$${fin.paid || 0}</div><div class="stat-lbl">المبلغ المستلم</div></div>
            <div class="td-stat"><div class="stat-icon" style="color:var(--warning);"><i class="fa-solid fa-hourglass-half"></i></div><div class="stat-num">$${fin.pending || 0}</div><div class="stat-lbl">المبلغ المعلق</div></div>
        `;
        document.getElementById('tdFinTable').innerHTML = `
            <tr><td style="font-weight:700;">الإجمالي المكتسب</td><td style="color:var(--success);font-weight:700;">$${fin.totalEarned || 0}</td></tr>
            <tr><td style="font-weight:700;">المبلغ المستلم</td><td style="color:var(--neon-blue);font-weight:700;">$${fin.paid || 0}</td></tr>
            <tr><td style="font-weight:700;">المبلغ المعلق (غير مصفى)</td><td style="color:var(--warning);font-weight:700;">$${fin.pending || 0}</td></tr>
            <tr><td style="font-weight:700;">آخر تحديث</td><td style="color:var(--text-secondary);font-size:0.8rem;">${formatDate(fin.lastUpdated)}</td></tr>
        `;
    }

    function renderArticles() {
        const articles = window.db.getArticles();
        document.getElementById('tdArticleInfo').textContent = articles.length + ' مقال';
        document.getElementById('tdArticleCount').textContent = articles.length;
        const tbody = document.getElementById('tdArticleTable');
        const empty = document.getElementById('tdArticleEmpty');
        if (articles.length === 0) { tbody.innerHTML = ''; empty.style.display = 'block'; return; }
        empty.style.display = 'none';
        tbody.innerHTML = [...articles].sort((a,b) => new Date(b.date||0) - new Date(a.date||0)).map(a => `
            <tr>
                <td><strong>${escHtml(a.title)}</strong></td>
                <td><span class="td-badge td-badge-blue">${a.category === 'education' ? 'تعليم' : a.category === 'tech' ? 'تكنولوجيا' : a.category === 'scholarships' ? 'منح' : a.category === 'career' ? 'تطوير مهني' : 'عام'}</span></td>
                <td style="color:var(--text-secondary);font-size:0.8rem;">${formatDate(a.date)}</td>
                <td><span class="td-badge td-badge-green">منشور</span></td>
                <td class="td-actions-cell">
                    <button class="td-btn td-btn-sm td-btn-outline" onclick="editTeacherArticle('${a.id}')"><i class="fa-solid fa-pen"></i></button>
                    <button class="td-btn td-btn-sm td-btn-danger" onclick="deleteTeacherArticle('${a.id}')"><i class="fa-solid fa-trash"></i></button>
                </td>
            </tr>
        `).join('');
    }

    // Global article functions
    window.editTeacherArticle = function(id) {
        const articles = window.db.getArticles();
        const a = articles.find(x => x.id == id);
        if (!a) return;
        document.getElementById('tdArticleId').value = a.id;
        document.getElementById('tdArticleTitle').value = a.title;
        document.getElementById('tdArticleExcerpt').value = a.excerpt;
        document.getElementById('tdArticleContent').value = a.content;
        document.getElementById('tdArticleCategory').value = a.category;
        document.getElementById('tdArticleImage').value = a.image || '';
        document.getElementById('tdArticleModal').classList.add('active');
    };

    window.deleteTeacherArticle = function(id) {
        if (!confirm('هل أنت متأكد من حذف هذا المقال؟')) return;
        window.db.deleteArticle(id);
        renderArticles();
        showToast('تم حذف المقال ✅');
    };

    window.generateTeacherArticleAI = function() {
        const title = document.getElementById('tdArticleTitle').value.trim();
        if (!title) { showToast('أدخل عنوان المقال أولاً', 'error'); return; }
        if (!window.AI_ASSISTANT) { showToast('المساعد الذكي غير متاح', 'error'); return; }
        const category = document.getElementById('tdArticleCategory').value;
        showToast('جاري توليد المقال بالذكاء الاصطناعي... ⏳', 'info');
        AI_ASSISTANT.generateArticle(title, category).then(result => {
            document.getElementById('tdArticleExcerpt').value = result.excerpt.replace(/<[^>]*>/g, '');
            document.getElementById('tdArticleContent').value = result.content;
            showToast('✅ تم توليد المقال بالذكاء الاصطناعي!');
        }).catch(() => {
            showToast('حدث خطأ في التوليد', 'error');
        });
    };

    renderTeacherUI();
});
